### ISSUE TITLE
Maps don't show some markers with coordinates

### ISSUE THREAD

**Issue by rolfmattes** [jxmono/mono-maps#21]
for example: 

http://dd.jillix.net/data/crm_gk_garageplus/528e71ecdd74152e60b4730b Kdnr: 412999

http://dd.jillix.net/data/crm_gk_garageplus/528e71f0dd74152e60b47c73 Kdnr: 81638

They have in the DB a location with coordiantes but the maps application does not load them on the garageplus.ch contact page: http://garageplus.ch/search. The data given to the map by the sag-api CRM module is correct. The same marker is correctly shown on the maps when displaying only one marker: http://grafmueller.garageplus.ch/?lang=de#kontakt

Maybe a problem with marker clustering?

**Comment by IonicaBizau** [comment]
Both of them are on the map:

### Graf & Müller Garage GmbH

> ![image](https://cloud.githubusercontent.com/assets/2864371/6710503/e5e87056-cd89-11e4-9517-ca9eb9d4546e.png)

### Revis-Motoren
> ![image](https://cloud.githubusercontent.com/assets/2864371/6710843/fbc89732-cd8b-11e4-9c9c-93962cf45351.png)

However, they have wrong positions. I opened this internally.
